<a href="https://colab.research.google.com/github/SanjnaReddy27/Fall-2023-CS5720/blob/main/Lesson3_ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a class Employee and then do the following

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [5]:
class Employee:
# Count the number of employees
    no_of_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.no_of_employees += 1

    def average_salary(self, employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees) if len(employees) > 0 else 0

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

# Instances of Employee class
employee1 = Employee("Sanjna", "Child", 90000, "IT")
employee2 = Employee("Nandhini", "Spouse", 65000, "Administration")
employee3 = Employee("Pavani", "Child", 72000, "Support")

# Instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Ram", "Spouse", 70000, "Finance")
fulltime_employee2 = FulltimeEmployee("Sita", "Child", 75000, "HR")

# Calling the average_salary function
employees = [employee1, employee2, employee3, fulltime_employee1, fulltime_employee2]
avg_salary = employee1.average_salary(employees)

print("The number of Employees:", Employee.no_of_employees)
print("Average salary of Employees:", avg_salary)

The number of Employees: 5
Average salary of Employees: 74400.0


2. Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

(you can NOT implement it via for loop)

In [6]:
import numpy as np

# Create a random vector of size 20 having only float in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

#  Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# replace the max in each row by 0 (axis=1)
#(Implemented it without for loop)
reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print(reshaped_array)

[[ 0.         10.27565943 14.16299592 15.8850175  17.94246123]
 [ 0.         14.33566602 10.4337653  14.87234673 13.91636839]
 [11.9302718  10.29369052 13.14423807  0.         11.97444539]
 [10.48115603  1.39181795  0.         12.61687366  9.11559564]]
